# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 06:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_no', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('DOB', models.DateField()),
                ('age', models.IntegerField()),
                ('address', models.CharField(max_length=200)),
                ('mob_no', models.IntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(7000000000)])),
                ('email', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
